# update os
sudo yum update -y
# set hostname as petclinic-dev-server
sudo hostnamectl set-hostname petclinic-dev-server
# install docker
sudo amazon-linux-extras install docker -y
sudo systemctl start docker
sudo systemctl enable docker
sudo usermod -a -G docker ec2-user
# install docker compose
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
# install JDK 11
sudo yum install java-11-amazon-corretto -y
# install Git
sudo yum install git -y
